version: '3.8'

services:
  wp:
    container_name: wp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WPGRAPHQL_VERSION: 1.14.4
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', '$SITE_URL' );
        define( 'WP_SITEURL', '$SITE_URL' );
        define( 'WP_DEFAULT_THEME', 'headless' );
        define( 'WP_AUTO_UPDATE_CORE', false );
    volumes:
      - wp-data:/usr/src/wordpress
    tmpfs:
      - /tmp
      - /run
    read_only: true
  
  nginx:
    container_name: nginx
    image: nginx:1.25.1-alpine-slim
    restart: always
    depends_on:
      - wp
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - wp-data:/var/www/html:ro
    ports:
      - 80:80

  db:
    container_name: db
    image: mariadb:10.11.4
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: $MYSQL_USER
      PMA_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 8880:80

volumes:
  wp-data:
  db-data: